site_name: "Melhores Ideias"
theme:
  name: 'material'
  logo: './files/logo.png'
  favicon: './files/ideia-icon.svg'
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
  palette:
    - scheme: default
      primary: dark-blue
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: slate
      primary: dark-blue
      toggle:
        icon: material/weather-sunny
        name: Light Mode

plugins:
  - encryptcontent:
      title_prefix: '🔒 '
      global_password: !ENV [PASSWORD, 'nidakai']
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: " "
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
      favicon_disabled: true
      favicon_size: 10
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false

markdown_extensions:
  - admonition
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format


extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - ./stylesheets/link-embeds.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js


nav:
  - Home: 'index.md'
  - Bot Afiliado: 'ideias/ideia-1.md'
  - Bot para MEI: 'ideias/ideia-2.md'
